### ISSUE TITLE
[BUG] - Lost Connection Loop

### ISSUE THREAD

**Issue by OGPanzerhund** [mwittrien/BetterDiscordAddons#2509] opened 2023-10-20 03:23 UTC
**Describe the bug**
Constant loop on the right side of the application saying "Discord lost the connection to the last device that was playing Spotify"

**To Reproduce**
Whenever I begin playing music on Spotify.

**Expected behavior**
The complete opposite.

**Screenshots**
![image_2023-10-19_222302728](https://github.com/mwittrien/BetterDiscordAddons/assets/33360827/b3757f36-db6b-4767-89ba-573675a847c0)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
N/A

**Comment by h0ethan04** [comment] 2023-10-20 03:44
Duplicate of #2507

**Closed** 2023-10-20 12:25 UTC
Labels: bug
