### ISSUE TITLE
Most plugins are broke on latest Canary

### ISSUE THREAD

**Issue by bgiesing** [mwittrien/BetterDiscordAddons#191] opened 2019-04-21 17:16 UTC
- ServerFolders doesn't work at all (no folders show up, pressing create folder in the menu does nothing, etc)
- ReadAllNotificationsButton is glitched even on stock theme ![](https://i.imgur.com/tDOTaWC.png)
- BetterSearchPage is missing icons ![](https://i.imgur.com/KDPZeKQ.png)
- ServerHider doesn't work at all (Manage Serverlist is empty, clicking hide server does nothing) ![](https://i.imgur.com/TAY6KFK.png)
- ShowImageDetails doesn't work at all (both Tooltip and header)
- TopRoleEverywhere doesn't work at all
- PinDMs works for channel list but not server list

BadgesEverywhere, ImageGallery, ReverseImageSearch, SendLargeMessages, and ThemeSettings work fine

**Comment by mwittrien** [comment] 2019-04-22 17:41
I am aware, i won't fix anything before Discord doesnt push the changes to stable, because Discord tends to change stuff and revert it back a lot

**Closed by mwittrien** 2019-04-22 17:41 UTC

**Comment by Reshiram110** [comment] 2019-04-23 23:14
This update was pushed to stable, and I can confirm that the server folders plugin is completely broken. It wont' load my folders, nor will it allow me to create any new ones.
