### ISSUE TITLE
[BUG] - BDFDB/PluginRepo

### ISSUE THREAD

**Issue by Elituz** [mwittrien/BetterDiscordAddons#2222] opened 2023-03-02 01:30 UTC
**Describe the bug**
I was trying to use Plugin Repo, so when I installed BDFDB, all I get is "React Component Error. I have version 3.1.0, and I have reinstalled multiple times. I have also tried version 3.0.9

**To Reproduce**
Install BDFDB, Install PluginRepo

**Expected behavior**
Not glitching, but instead glitching.

**Discord Build (stable, ptb or canary):**
Discord Version v1.0.9011

![image](https://user-images.githubusercontent.com/86256555/222307345-bc574d77-68b6-4283-ab52-4649b7396f2e.png)
em here.

**Comment by ScrubN** [comment] 2023-03-02 02:05
To be more helpful, here is the error when trying to open the plugin repo:
![image](https://user-images.githubusercontent.com/72096833/222311864-42d9dbb6-4928-4e8c-af37-2381ea26c626.png)

**Comment by ggtylerr** [comment] 2023-03-02 04:59
Duplicate of #2219

**Closed** 2023-03-02 05:43 UTC
Labels: bug, duplicate
