### ISSUE TITLE
[BUG] - BDFDB lags

### ISSUE THREAD

**Issue by Piripe** [mwittrien/BetterDiscordAddons#2073] opened 2022-11-26 15:20 UTC
**Describe the bug**
Extreme performances issue.
When I open a text channel on a big server (Ex: BetterDiscord) I have extreme lags, my Discord run at ~5FPS if it's not under and when I try to change the channel, it takes up to 30 seconds or crash directly.

Note: I tried without BDFDB and I haven't this performance issue.

**To Reproduce**
Open the BetterDiscord Discord server (And if you haven't the issue, idk how you can reproduce)

**Expected behavior**
I don't want this performance issue.

**Screenshots**
My installed plugins (Without BDFDB because I can't use Discord with it, it's just impossible) :
![image](https://user-images.githubusercontent.com/77517308/204095976-92d4715a-8d93-43ab-8ced-087410cc8773.png)

I also have a performance profile:
https://drive.google.com/file/d/1Uad04XJhEVHpZR9jw8LxGYf73LQ1bCXe/view?usp=share_link
(I recorded it 3 times to successfully get it without a crash)

**Discord Build (stable, ptb or canary):**
stable

**Comment by darkinger231** [comment] 2022-11-27 16:17
i have this same issue

**Comment by IceNet** [comment] 2022-11-27 22:23
Same

**Comment by zXzLenin** [comment] 2022-12-13 13:31
Also experiencing alot of lag while switching channels, servers and pretty much everything in discord: 
![jqWdRs7o4U (2022-12-13) (08-28-17)](https://user-images.githubusercontent.com/118400371/207334478-d1b48907-a43a-4d25-9712-69d61e427987.jpg)

**Comment by cyrus01337** [comment] 2022-12-15 03:31
From my experience and as stated in OP's description, disabling BDFDB does resolve this, though I'm unsure how useful appending "me too!" messages could be. For now, feel free to disable the plugin.

Seems like the issue is consistent across OSes, haven't seen an issue raised for Mac yet though I'd assume once a fix has been applied it will work it's magic.

**Comment by ThatXliner** [comment] 2023-01-05 14:37
I don’t experience lag anymore

> I have extreme lag
> <img alt="Screen Shot 2022-12-06 at 4 59 35 PM" width="745" src="https://user-images.githubusercontent.com/66848002/206061792-4226f047-5167-4d44-a583-37c2c331bafa.png">
> <img alt="Screen Shot 2022-12-06 at 4 59 49 PM" width="181" src="https://user-images.githubusercontent.com/66848002/206061833-b8cf9fb8-a879-4945-958a-fc08ccffce2d.png">

Probably after updating

**Closed** 2023-01-17 16:40 UTC
Labels: bug
