### ISSUE TITLE
Plugin repo Doesn't work

### ISSUE THREAD

**Issue by Ciro8002** [mwittrien/BetterDiscordAddons#2042] opened 2022-11-13 18:43 UTC
**Describe the bug**
When I insert the plugin in the plugins folder and also download the BDFBD and I get the discord notification click open and opens a black screen and if I press esc removes it and nothing works.
**To Reproduce**
the bug occurs when I start discord and I can’t find the button to go to Plugin-repo.

![image](https://user-images.githubusercontent.com/118130332/201538663-f5021a64-9c48-44fe-b3d5-00f406d3855f.png)

![image](https://user-images.githubusercontent.com/118130332/201538685-e1f76e10-26bf-41d4-98a7-51a0f2b8338c.png)
![image](https://user-images.githubusercontent.com/118130332/201538696-e37e569b-fcd5-40aa-adcb-73a7df005ee4.png)

**Comment by jogerj** [comment] 2022-11-14 19:48
duplicate of #2025

**Comment by Crypt0Beaver** [comment] 2022-11-14 22:39
@all, please check the discord server. @mwittrien  sent an announcement, the recent discord update broke the BDKDB library and plugins won't work. He'll fix them on his return.

**Comment by mwittrien** [comment] 2022-11-15 22:13
#2047

**Closed by mwittrien** 2022-11-15 22:13 UTC
Labels: bug
