### ISSUE TITLE
[BUG] - Notification Sounds

### ISSUE THREAD

**Issue by diyachan** [mwittrien/BetterDiscordAddons#1308] opened 2022-01-11 07:21 UTC
**Describe the bug**
Default Discord's and custom notification sounds are played together instead of just the custom sound

**To Reproduce**
Get any message notification (mentions, DMs)

**Expected behavior**

**Screenshots**
none, it's audio

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**

**Comment by ImDini** [comment] 2022-01-11 09:18
Yeah I need this fix, discord default sounds breaking my headset while I still hear the plugin sounds.

**Comment by Merthew** [comment] 2022-01-11 10:08
Just hopped on to check if someone had reported this already, glad to see someone else has the issue and its not just my computer being dumb.

**Comment by Kurotaku-sama** [comment] 2022-01-11 15:38
You can disable the default notifiactions in the settings while waiting for a fix for this to prevent the default sounds.

I also get a "Message notification" when a call starts before the call sound appear since the last DC update.

**Comment by ImDini** [comment] 2022-01-11 22:47
> You can disable the default notifiactions in the settings

Where?

**Comment by mwittrien** [comment] 2022-01-11 22:50
Discord settings

**Comment by Korhu** [comment] 2022-01-13 18:18
> 

Ive tried restarting, and even reinstalling better discord, in fact, not the custom sounds do not play at all unless I go into the plugin settings, and then leave the plug in settings

**Comment by ImDini** [comment] 2022-01-14 05:33
> > 
> 
> Ive tried restarting, and even reinstalling better discord, in fact, not the custom sounds do not play at all unless I go into the plugin settings, and then leave the plug in settings
> 
> Edit: ALso under which setting can you disable the default notification
They meant turning off all sounds which not only removes sounds but removes even the custom sounds. The custom sounds don't even work that way lol. This needs to be updated

**Comment by MrDucc** [comment] 2022-01-14 23:26
> > 
> 
> Ive tried restarting, and even reinstalling better discord, in fact, not the custom sounds do not play at all unless I go into the plugin settings, and then leave the plug in settings
> 
> Edit: ALso under which setting can you disable the default notification

Settings > Notifications > Sounds

**Comment by ImDini** [comment] 2022-01-14 23:51
Nice I was stating an honest experience I'm having with what "dev" suggested and they removed my comment. If you disable default notifications it does not work, it'll work for the time when you disable them. After any launch after that all sounds will be removed, not just default. Try it, it's reproduceable.

**Comment by BlueStarBRS** [comment] 2022-01-15 13:16
> Its fixed for me by restarting discord

its still buggy by me its playing everytime everything together

**Comment by BlueStarBRS** [comment] 2022-01-15 13:18
so im so glad if you release a fixed version thanks.

**Comment by mwittrien** [comment] 2022-02-12 19:51
As much as i want to fix this issue, i simply can't reproduce it,
everything works fine for me and no default sounds are playing over the custom ones

**Comment by Kurotaku-sama** [comment] 2022-02-12 20:39
> As much as i want to fix this issue, i simply can't reproduce it, everything works fine for me and no default sounds are playing over the custom ones

If you have all notifications enabled it occurs. I have the newest BD and DC Version. And we get even the notification sound for the message that a call is starting.
![grafik](https://user-images.githubusercontent.com/54163348/153727506-7e7f583f-52f5-4cc0-aa25-65ec66cb72ea.png)

**Comment by Kurotaku-sama** [comment] 2022-02-12 20:51
I know but I just mentioned this problem as well since it start doing the sounds as well twice

**Comment by Nyro46** [comment] 2022-02-12 20:58
Want to add that I'm still having issues with this too since Discord updated a month ago.
For me it will play the custom sounds normally when I'm pinged, but regular server notifs play ONLY the default sound, and DM notifs play both.

**Closed** 2022-02-12 22:28 UTC
Labels: bug
