### ISSUE TITLE
Server Folders Bug

### ISSUE THREAD

**Issue by T0xicFX** [mwittrien/BetterDiscordAddons#237] opened 2019-07-17 08:15 UTC
Yesterday i got a bug that glitches the position of the folders i made
Preview: http://prntscr.com/og5pyf

**Comment by KaKi87** [comment] 2019-07-17 09:13
This is not a bug, but an incompatibility due to the last Discord client update.
However, I can confirm this is happening.

**Comment by silent** [comment] 2019-07-17 09:22
#235 already exists

**Comment by KaKi87** [comment] 2019-07-17 09:29
Duplicate of #235

**Comment by TotoShampoin** [comment] 2019-07-17 10:54
I don't really mind being duplicated, that only shows it being an actual issue easier... 
But yeah, you duped my post #235

**Closed** 2019-07-17 11:10 UTC
