### ISSUE TITLE
[BUG] - SplitLargeMessages v1.7.9

### ISSUE THREAD

**Issue by Thqrn** [mwittrien/BetterDiscordAddons#1955] opened 2022-10-25 21:52 UTC
**Describe the bug**
The bug causes messages to be sent twice.

**To Reproduce**
Send a message.

**Expected behavior**
The message should send a single time.

**Screenshots**
[Streamable link.](https://streamable.com/l71atn)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Disabling the plugin fixed this issue, and the issue happened again upon re-enabling it.

**Comment by defaultkid99** [comment] 2022-10-25 22:40
happens to me also

**Comment by nhan000** [comment] 2022-10-26 02:28
duplicate of https://github.com/mwittrien/BetterDiscordAddons/issues/1951

**Closed** 2022-10-26 05:07 UTC
Labels: bug
